name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
    paths:
      - Dockerfile
      - main.py
      - overlay_generator.py
      - requirements.txt
      - settings.py
      - validate_settings.py
  pull_request:
    branches: [ "main" ]
    paths:
      - Dockerfile
      - main.py
      - overlay_generator.py
      - requirements.txt
      - settings.py
      - validate_settings.py
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and Push Image
      run: |
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_TOKEN }}
        docker build . --file Dockerfile --tag dweagle/status-overlay:latest
        docker push dweagle/status-overlay:latest
